"use strict";
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const worker=read('tools/uploader/worker.js'), uploader=read('src/Uploader.cs');
const workspace=read('src/YouTubeWorkspacePanel.cs'), backend=read('src/YouTubeBackend.cs');
const navigation=read('tools/uploader/youtube-open-today.js');
assert.match(worker,/restartAlreadyRunningProfile\(\)/,'Recover missing Dolphin automation endpoint');
assert.match(uploader,/result\.Success=msg\.success/,'Respect worker failure');
assert.match(uploader,/ValidateCommon\(false,channelsFilter\)/,'Validate requested workspace selection');
assert.match(uploader,/ValidateExternalChannels/);
assert.match(workspace,/RunLinkWatch/);
assert.match(worker,/job\.watchDirectLinks/);
assert.match(worker,/Профиль оставлен открытым/);
assert.match(uploader,/ParseDirectWatchLinks/);
assert.match(uploader,/MoveFileReplacing/);
assert.match(uploader,/ch\.Kind=packKind/);
assert.match(backend,/RunRuMeshWatchAsync/);
assert.match(workspace,/GetCheckedChannelsForMarket\("RU"\)/,'RU button must use RU selection');
assert.match(backend,/channelUrlsByProfileId, "RU"\)/,'Pass explicit RU market to backend');
const mesh=uploader.slice(uploader.indexOf('async Task CrossWatchMesh('),uploader.indexOf('async Task CrossWatchLinks('));
assert.match(mesh,/const int batchSize=5/,'Old preference four must not reduce the requested batch');
assert.match(mesh,/NormMarket\(ch.Market\)==market/,'Keep RU/EN profiles separated');
assert.match(mesh,/targets.Skip\(offset\).Concat\(targets.Take\(offset\)\)/,'Rotation must retain every channel');
assert.doesNotMatch(mesh,/Where\(ch=>!string.Equals/,'Own channel is also a navigation target');
assert.doesNotMatch(mesh,/PublishedUrl|BuildMeshCatalogVideos|SaveMeshCatalog/,'Upload history must not select today video');
assert.match(mesh,/await Task.WhenAll\(tasks\)/);
assert.match(mesh,/finally[\s\S]*?StopProfileRequired/,'Close profiles on success, failure and cancellation');
assert.match(mesh,/if\(closeErrors.Count>0\)throw/,'Unconfirmed close must block the next batch');
assert.match(worker,/if \(!job\.openTodayOnly && !job\.watchMesh\) try/,'Navigation must not wait for external IP services');
assert.match(worker,/openChannelsWatch\(page, targets, navigationJob/);
assert.match(worker,/2026-10-01-watch-grid/);
assert.match(worker,/job.openTodayOnly \|\| job.watchMesh/,'C# alone owns closure of navigation profiles');
const playback=read('tools/uploader/youtube-playback.js');
assert.match(playback,/waitForVideoEnd/);
assert.match(playback,/Лайк поставлен/);
assert.match(playback,/Видео закончилось/);
assert.match(navigation,/openChannelsWatch/);
assert.match(navigation,/navigateTodayVideo/);
assert.match(navigation,/resourceType\(\) === "media"/);
assert.match(navigation,/pauseCurrentVideo\(page[,)]/);
assert.match(playback,/if \(!\(await isVideoLiked\(page\)\)\) await likeCurrentVideo/,'Like only after playback ends');
console.log('OK: watch_regressions.js (navigation, selection and closure)');
